backend: 
    name: github
    repo: AdamanskaHub/Simon

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: MegaTitle, name: megatitle, widget: string}
          - {label: MegaTitlex, name: megatitlex, widget: string}
          - {label: SubTitle, name: subtitle, widget: string}
          - {label: TitleOne, name: titleone, widget: string}
          - {label: ParaOne, name: paraone, widget: string}
          - {label: TitleTwo, name: titletwo, widget: string}
          - {label: ParaTwo, name: paratwo, widget: string}
          - {label: TitleThree, name: titlethree, widget: string}
          - {label: ParaThree, name: parathree, widget: string}